### ISSUE TITLE
1.17 fabric - random entities are shown in the same color as "friendly mobs"

### ISSUE THREAD

**Issue by gregCubed** [ToroCraft/ToroHealth#103]
In addition to having the same issue as another user (wherein the targeted mob does not move with the HUD display, but rather stays in the top left), I have an issue where random blocks/entities in the world turn a bright green (or whatever color, I assume, is the color used for "health indicator/HP added".
So far, I have seen bells turn a bright green when looked at (it's not really an exact science of when it triggers, but you can move your cursor over the block and it consistently will turn bright green). I have also observed this with beds, leads (on a fence), and player heads in multiplayer (but rest assured this issue also occurs in singleplayer worlds, too).
I know this issue is not limited to my resource pack as it happened with the default pack (first image) as well as the second (FaithfulVenom 32x pack).
![image](https://user-images.githubusercontent.com/54684706/123915868-cbc34c00-d935-11eb-97d2-3371cfd6301f.png)
![image](https://user-images.githubusercontent.com/54684706/123916449-83f0f480-d936-11eb-82dc-c640a541913e.png)

**Comment by frodare** [comment]
Thanks for reporting this. I will update to the latest fabric version and work on a fix for the next release.

**Comment by frodare** [comment]
File torohealth-1.17-fabric-6.jar fixes the issue with entity location.  I haven't been able to reproduce the color issue yet.

**Comment by frodare** [comment]
I never was able to reproduce this issue, but I did hear of it from multiple people.  Was this fixed in the latest versions?

**Comment by gregCubed** [comment]
Well, I've found that it goes away with the F3 menu pulled up, but outside of that it still happens pretty regularly. If it helps, I can list the mods I'm using in conjunction with this one as well as my specs.

**Comment by frodare** [comment]
Bummer, I was hoping it was fixed in the later versions.  If you can narrow it down to 3 mods or less then yes, that would be helpful.

**Comment by MarinaMarissa** [comment]
> Bummer, I was hoping it was fixed in the later versions. If you can narrow it down to 3 mods or less then yes, that would be helpful.

@frodare 
mods:
fabric-api-0.37.1+1.17.jar
list.txt
modmenu-2.0.4.jar
optifabric-1.11.18.jar
preview_OptiFine_1.17.1_HD_U_G9_pre32.jar
torohealth-1.17.1-fabric-10.jar


![2021-07-26_10 21 57](https://user-images.githubusercontent.com/61768909/126924851-91d857e5-576e-4b7b-9f5e-70989f856373.png)
![2021-07-26_10 22 04](https://user-images.githubusercontent.com/61768909/126924856-4887d6fb-01d6-48af-9500-0183a78cc5b7.png)
![2021-07-26_10 22 17](https://user-images.githubusercontent.com/61768909/126924858-f4b7bd03-cc56-4768-bbef-e1ba7078ddd3.png)
![2021-07-26_10 22 35](https://user-images.githubusercontent.com/61768909/126924863-99ef65c4-1a4a-4c54-b14d-c0fd1f738500.png)
![2021-07-26_10 23 57](https://user-images.githubusercontent.com/61768909/126924865-9e870b6f-4d5f-49fe-96d9-9b9076abd640.png)
![2021-07-26_10 24 17](https://user-images.githubusercontent.com/61768909/126924867-213dc3bc-4937-4105-b65b-3ab8dd3e3c56.png)


![2021-07-26_10 22 23](https://user-images.githubusercontent.com/61768909/126924905-45958cfd-dc64-42aa-b94e-e843f714f055.png)

**Comment by zeriley** [comment]
This sounds similar to when we would modify the GL stuff then not set it back.  Can you get the current RenderSystem state before you modify it here: https://github.com/ToroCraft/ToroHealth/blob/master/src/main/java/net/torocraft/torohealth/bars/HealthBarRenderer.java#L164

Then reset it to that before you leave that method?  Don't know why that would only sometimes change the color like that, but maybe certain renderers don't set the state of the RenderSystem properly before using it.

**Comment by frodare** [comment]
This might be fixed torohealth-1.17.1-fabric-11.jar.  I was never able to reproduce this issue, so I will leave it open for awhile for anyone to report back if the issue is still occurring.

**Comment by gregCubed** [comment]
Seems like whatever you did fixed it.

Running the following:
`fabric-api-0.37.2+1.17.jar
litematica-fabric-1.17.1-0.0.0-dev.20210713.103711.jar
malilib-fabric-1.17.1-0.10.0-dev.24.jar
modmenu-2.0.4.jar
optifabric-1.11.18.jar
plasmovoice-fabric-1.0.11.jar
preview_OptiFine_1.17.1_HD_U_G9_pre32.jar
torohealth-1.17.1-fabric-11.jar`
