### ISSUE TITLE
[Request] Floating Numbers only mode

### ISSUE THREAD

**Issue by NillerMedDild** [ToroCraft/ToroHealth#67]
I would like to request a config for only having the floating damage numbers, not entity / bar / skin. Disabling bar seems to make the floating numbers disappear, not sure if that's intentional.

I hope you'll consider it :)

**Comment by frodare** [comment]
You are talking about the damage particles that pop out of entities when you hit them, not the damage number at the right side of the bar, correct?

**Comment by NillerMedDild** [comment]
Yes that is correct :)

**Comment by frodare** [comment]
OK, yes that sounds like a bug then.  I meant to test this out before and never got around to it. Thanks for posting an issue here, it is easier to track.

**Comment by frodare** [comment]
Sorry I missed this on my last release.  I have cleaned up the issues on this project a bit and then saw this one again.  However, I just tested and it appears that this is no longer an issue.  Maybe I fixed it by accident?  Please feel free to comment back here, but for now I will close the issue.

**Comment by NillerMedDild** [comment]
This is still an issue in `torohealth-1.16.4-forge-4`

My config: 
```json
{
    "watchForChanges": true,
    "hud": {
        "distance": 60,
        "x": 4.0,
        "y": 4.0,
        "scale": 1.0,
        "hideDelay": 20,
        "anchorPoint": "TOP_LEFT",
        "showEntity": false,
        "showBar": false,
        "showSkin": false
    },
    "bar": {
        "damageNumberType": "LAST",
        "friendColor": 16711935,
        "friendColorSecondary": 8388863,
        "foeColor": -16776961,
        "foeColorSecondary": -2147483393
    },
    "inWorld": {
        "mode": "NONE",
        "distance": 60.0,
        "onlyWhenLookingAt": false,
        "onlyWhenHurt": false
    },
    "particle": {
        "show": true,
        "damageColor": 16711680,
        "healColor": 65280
    }
}
```
